name: Testing

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: |
          sudo apt-get install -y \
              libglu1-mesa-dev \
              libglew-dev \
              xorg-dev
      - run: pip install -r requirements.txt
      - run: pip install -e .
      - run: python -c 'import evogym; print(f"{evogym.__name__} was loaded.")'
