name: Testing

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os:
          - "ubuntu-18.04"
          - "ubuntu-22.04"
        python:
          - "3.7"
          - "3.8"
          - "3.9"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install deb dependencies
        run: sudo apt-get install -y xorg-dev libglu1-mesa-dev libglew-dev
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Cache python wheel packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: wheel-cache-${{ hashFiles('requirements.txt') }}
      - name: Install evolution gym
        run: pip install -e .
      - name: Run test
        run: python -c 'import evogym; print(f"{evogym.__name__} was loaded.")'
