name: Testing

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os:
          - "ubuntu-22.04"
          # - "ubuntu-latest"
        python:
          # - "3.7"
          - "3.8"
          # - "3.9"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install deb dependencies
        run: sudo apt-get install -y xorg-dev libglu1-mesa-dev libglew-dev xvfb
      # - name: Cache python wheel packages
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/pip
      #     key: wheel-cache-${{ hashFiles('requirements.txt') }}
      - name: Install evolution gym
        run: python3 setup.py install
      - name: Install python dependencies
        run: pip3 install -U pip==23.0.1
      - name: Install python dependencies
        run: pip3 install -r requirements.txt
      - name: Run test
        run: |
          cd tests
          xvfb-run python3 -m unittest test_render.py
