name: Testing

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: sudo apt-get install -y xorg-dev libglu1-mesa-dev
      - run: pip install .
        env:        
          GLEW_INCLUDE_DIRS: evogym/simulator/externals/glew/include
          GLEW_LIBRARIES: evogym/simulator/externals/glew
